name: wallpaperclub
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  cached_network_image: ^2.5.0
  image_gallery_saver: ^1.6.7
  permission_handler: ^5.0.1+1
  random_string: ^2.1.0
  url_launcher: ^5.7.10
  cupertino_icons: ^1.0.1  
  google_fonts: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true