name: wallpaperclub
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  cupertino_icons: ^1.0.1  
  google_fonts: ^1.1.1
  cached_network_image: ^2.2.0+1
  permission_handler: ^4.0.0
  shared_preferences: ^0.5.7+3
  dio: ^3.0.9
  esys_flutter_share: ^1.0.2
  file_utils: ^0.1.4
  path_provider: ^1.6.9
  fluttertoast: ^4.0.1
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true